services:
  web:
    build: .
    container_name: delivery_service
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///data/delivery.db
    restart: unless-stopped